Vagrant.configure("2") do |config|
	config.vm.define "control01" do |control01|
		control01.vm.box = "centos/7"
#		control01.vm.box = "nrel/CentOS-6.5-x86_64"
		control01.vm.hostname = "control01"
		control01.vm.network "private_network", ip: "192.168.1.50"
	end
	config.vm.define "node01" do |node01|
		node01.vm.box = "centos/7"
#		node01.vm.box = "nrel/CentOS-6.5-x86_64"
		node01.vm.hostname = "node01"
		node01.vm.network "private_network", ip: "192.168.1.51"
	end
	config.vm.define "node02" do |node02|
		node02.vm.box = "centos/7"
#		node02.vm.box = "nrel/CentOS-6.5-x86_64"
		node02.vm.hostname = "node02"
		node02.vm.network "private_network", ip: "192.168.1.52"
	end
	config.vm.define "node03" do |node03|
		node03.vm.box = "centos/7"
#		node03.vm.box = "nrel/CentOS-6.5-x86_64"
		node03.vm.hostname = "node03"
		node03.vm.network "private_network", ip: "192.168.1.53"
	end
end
