# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "ngmonsrv" do |ngmonsrv|
#		ngmonsrv.vm.box = "centos/7"
		ngmonsrv.vm.box = "nrel/CentOS-6.5-x86_64"
		ngmonsrv.vm.hostname = "ngmonsrv"
		ngmonsrv.vm.network "private_network", ip: "192.168.1.50"
#		ngmonsrv.vm.boot_timeout = 600
	end
	config.vm.define "web01" do |web01|
#		web01.vm.box = "centos/7"
		web01.vm.box = "nrel/CentOS-6.5-x86_64"
		web01.vm.hostname = "web01"
		web01.vm.network "private_network", ip: "192.168.1.51"
#		web01.vm.boot_timeout = 600
	end
end
