Vagrant.configure("2") do |config|
	config.vm.define "elkctrl01" do |elkctrl01|
		elkctrl01.vm.box = "centos/7"
#		elkctrl01.vm.box = "nrel/CentOS-6.5-x86_64"
		elkctrl01.vm.hostname = "elkctrl01"
		elkctrl01.vm.network "private_network", ip: "192.168.1.60"
	end
	config.vm.define "node01" do |node01|
		node01.vm.box = "centos/7"
#		node01.vm.box = "nrel/CentOS-6.5-x86_64"
		node01.vm.hostname = "node01"
		node01.vm.network "private_network", ip: "192.168.1.61"
	end
	config.vm.define "node02" do |node02|
		node02.vm.box = "centos/7"
#		node02.vm.box = "nrel/CentOS-6.5-x86_64"
		node02.vm.hostname = "node02"
		node02.vm.network "private_network", ip: "192.168.1.62"
	end
	config.vm.define "node03" do |node03|
		node03.vm.box = "centos/7"
#		node03.vm.box = "nrel/CentOS-6.5-x86_64"
		node03.vm.hostname = "node03"
		node03.vm.network "private_network", ip: "192.168.1.63"
	end
end
