# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "dev01" do |dev01|
		dev01.vm.box = "ubuntu/xenial64"
#		dev01.vm.box = "centos/7"
#		dev01.vm.box = "nrel/CentOS-6.5-x86_64"
		dev01.vm.hostname = "dev01"
		dev01.vm.network "private_network", ip: "192.168.1.50"
#		dev01.vm.boot_timeout = 600
	end
end
